### ISSUE TITLE
Would you like property-based tests?

### ISSUE THREAD

**Issue by Zac-HD** [asottile/tokenize-rt#61]
Heya!  I use and love many of your tools, and have even built on top of them with `shed`.  When I saw `tokenize-rt` I thought of my demonstration tests that the stdlib version doesn't roundtrip, and wondered if you'd like a PR adding similar tests?

https://github.com/Zac-HD/stdlib-property-tests/blob/b5ef97f9e7fd1b0e7a028823e436f78f374cf0dc/tests/test_source_code.py#L87-L133

(adds a test-time dependency on Hypothesis, LibCST, etc)

**Comment by asottile** [comment]
my experience with hypothesis is that it adds *significant* test time and I don't think it would add much (?) value given the trade off there

additionally, libcst is dead -- without a rewrite to PEG it will be unable to handle new syntax

I did try the few `@example`s and they seem to work fine (though `'\n\\\n'` was recently promoted to a `SyntaxError` so that one didn't pass)

**Comment by Zac-HD** [comment]
Fair enough! I often use a pattern of "explicit examples in CI, ongoing search on demand/overnight". In this case I'll try leaving it running in hypofuzz for a while and see if it finds anything interesting.

I'm hoping that libcst will update to handle the new grammar - but if not, Guido seems interested in helping update Hypothesmith to use it directly instead. We'll see, I guess.
