### ISSUE TITLE
Why not send upstream?

### ISSUE THREAD

**Issue by ItzSwirlz** [asottile/tokenize-rt#77]
Pyupgrade and a lot of your other projects rely on this tokenize-rt program; it's the same thing but patched with a few extras. This is basically extra work for the Debian Python Team (which I am trying to package pyupgrade) and you, so why not send the stdlib tokenize changes upstream? You are more better to do it than I am because you already have several packages with lots of downloads/uses.

**Comment by asottile** [comment]
please don't package my stuff if this is the attitude you're going to take

**Comment by ItzSwirlz** [comment]
Looking back I was tired and kinda wrote it mean, but I'm just saying that this should be sent upstream. Most maintainers don't find a reason to package this, and since it relies on other packages that you are well known for your other tools, you may not have luck in the packaging world. So be it then.

**Comment by pabs3** [comment]
@asottile I am sorry for causing this issue to be filed.

I was on the Debian Python chat when @ItzSwirlz was looking for help with their package of tokenize-rt. I misunderstood that tokenize-rt is wrapper for Python stdlib tokenize, I thought it was a fork of Python stdlib tokenize, so I advised them to ask you to merge tokenize-rt into the Python stdlib tokenize, leading to this issue. I'm sorry for not investigating more closely and causing this issue to be filed. Given the misunderstanding and this issue was not the fault of @ItzSwirlz, I hope you will be OK with them adding a package of tokenize-rt to Debian if they decide to do that.
